version: '3.9'

services:
  nginx:
    container_name: django_crm_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - media:/code/media
      - static:/code/static
    depends_on:
      - app
    networks:
      - default_network
    restart: unless-stopped

  app:
    container_name: django_crm_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - static:/code/static
      - media:/code/media
    depends_on:
      - db
    networks:
      - default_network
    restart: unless-stopped
    environment:
      DEBUG: ${DEBUG:-false}

  db:
    image: postgres:latest
    container_name: django_crm_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - default_network
    restart: unless-stopped

volumes:
  pgdata: { }
  media: { }
  static: { }

networks:
  default_network: { }