# Generated by Django 5.1.5 on 2025-01-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerSupport', '0002_alter_customerrequest_contract_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequest',
            name='subject',
            field=models.CharField(blank=True, help_text='Выберите тему обращения', max_length=200, verbose_name='Тема обращения'),
        ),
    ]
