# Generated by Django 5.1.5 on 2025-01-28 09:40

import src.apps.CustomerSupport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerSupport', '0003_alter_customerrequest_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequest',
            name='subject',
            field=models.CharField(blank=True, choices=[], help_text='Выберите тему обращения', max_length=200, validators=[], verbose_name='Тема обращения'),
        ),
    ]
